config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/dashboard/my-tracks' => "dashboard#my_tracks", :as => :user_root
  root to: 'pages#home'
  get '/dashboard/my-tracks', to: 'dashboard#my_tracks'
  get '/dashboard/track-library', to: 'dashboard#track_library'
  get '/dashboard/team', to: 'dashboard#team'
  get '/dashboard/profile', to: 'dashboard#profile'
  get '/dashboard/settings', to: 'dashboard#settings'

  resources :tracks, except: %i[index show] do
    resources :steps, only: %i[create destroy]
    resources :assignments, only: %i[create]
  end

  resources :assignments, only: %i[show destroy] do
    resources :step_scores, only: %i[update]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def my_tracks
    @assignments = policy_scope(Assignment, policy_scope_class: AssignmentPolicy::Scope)
  end

  def track_library
    @employees_of_manager = User.where(user_id: current_user)
    if current_user.is_manager?
      @tracks = policy_scope(Track, policy_scope_class: TrackPolicy::Scope)
    else
      authorize self
    end
    @track = Track.new

    # The line below is a reminder so that we remember how to authorize
    # a single instance of another model within the dashboard.
    # authorize @track, :show?, policy_scope_class: TrackPolicy
  end

  def team
    authorize self
    @manager = current_user.is_manager? ? current_user : User.find(current_user.user_id)
    @team = User.where(user_id: @manager).order(created_at: :asc)
  end

  def profile
    authorize self
  end

  def settings
    authorize self
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def dashboard_view?(params)
    return true if params[:controller] == 'dashboard'
    return true if params[:controller] == 'tracks' && params[:action] == 'edit'
    return true if params[:controller] == 'tracks' && params[:action] == 'create'
    return true if params[:controller] == 'assignments' && params[:action] == 'show'
  end

  def dashboard_path
    return dashboard_track_library_path if current_user.is_manager?

    return dashboard_my_tracks_path
  end
end

app/views/dashboard/_assign_track_modal.html.erb
<!-- Modal for assign training -->
<div class="modal fade" id=<%= "modal#{track.id}" %> tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong class="modal-title" id="exampleModalLabel">Assign training to a team member</strong>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [track, Assignment.new] do |f| %>
          <%# TODO: dropdown should not display user who already have this track assigned %>
          <%= f.association :user, collection: @employees_of_manager, label_method: :first_name, label: false, selected: @employees_of_manager.first %>
          <%= f.button :submit, "Assign", id: 'submit', class: 'btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/my_tracks.html.erb
<h5 class="my-tracks__ready">Ready to jump back in, <%= current_user.first_name %>?</h5>

<div class="container" style="max-width: 900px;">
  <div class="row">
    <% @assignments.each do |assignment| %>
    <div class="col-12 col-md-6 col-lg-4 d-flex justify-content-center">
      <%= link_to assignment_path(assignment) do %>
      <div class="track-card mb-3">
        <h3><%= assignment.track.title %></h3>
        <div class="track-card__score">
        <% if assignment.completed? %>
          <i class="far fa-check-circle completed"></i>
          <span>All steps completed</span>
        <% else %>
          <i class="far fa-circle"></i>
          <span><%= "#{assignment.num_of_steps_completed}/#{assignment.num_of_steps} #{"step".pluralize(assignment.num_of_steps)} completed" %></span>
        <% end %>
        </div>
        <p class="track-card__date">Assigned on: <%= assignment.created_at.strftime("%d-%m-%Y") %></p>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/settings.html.erb
<div class="container">
  <%= button_to 'Delete last assignment', assignment_path(Assignment.last), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/dashboard/team.html.erb
<!-- <h5 class="my-tracks__ready">Welcome to <%= @manager.first_name %>'s team</h5> -->

<h5 class="my-tracks__ready">Team manager</h5>
<div class="container" style="max-width: 900px;">
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <div class="track-card mb-3" style.color="yellow">
        <%= image_tag "#{@manager.first_name}.jpg",
            class: "avatar #{current_user == @manager ? "current" : ""}  mb-2 mx-auto d-block",
            alt: "avatar" %>
        <h3><%= @manager.first_name%> <%= @manager.last_name %></h3>
        <p style="font-size: 0.8rem;"><%= @manager.role %> </p>
      </div>
    </div>
  </div>

  <h5 class="my-tracks__ready mt-5">Team members</h5>
  <div class="row">
    <% @team.each do |team_member| %>
      <div class="col-12 col-md-6 col-lg-4 d-flex justify-content-center">
        <div class="track-card mb-3">
          <%= image_tag "#{team_member.first_name}.jpg",
              class: "avatar #{current_user == team_member ? "current" : ""} mb-2 mx-auto d-block",
              alt: "avatar" %>
          <h3><%= team_member.first_name%> <%= team_member.last_name %></h3>
          <p style="font-size: 0.8rem;"><%= team_member.role %> </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboard/track_library.html.erb
<div class="container my-2" style="max-width: 900px;">
  <!-- Button for create training Modal -->
  <button class="btn-secondary mb-3" data-toggle="modal" data-target="#createTrackModal">Create training</button>

  <!-- Modal for create training -->
  <div class="modal fade" id="createTrackModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <strong class="modal-title" id="exampleModalLabel">Name your training</strong>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(@track) do |f| %>
            <%= f.input :title, input_html: { maxlength: '28' }, label: false %>
            <%= f.button :submit, "Save training", id: 'submit', class: 'btn-secondary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <h5 class="my-tracks__ready">Trainings you created</h5>
  <div class="row mb-3">
    <% @tracks.where(user: current_user).each do |track| %>
      <div class="col-12 col-md-6 col-lg-4 d-flex justify-content-center">
        <div class="track-card mb-3 d-flex flex-column align-items-center">
          <h3><%= link_to track.title, edit_track_path(track), class: 'link-styling' %></h3>
          <p>Contains <%= track.steps.count %> steps</p>
          <!-- Button for assign training modal -->
          <button class="btn-secondary-outline mt-3" data-toggle="modal" data-target=<%= "#modal#{track.id}" %>>Assign</button>
          <%= render 'assign_track_modal', track: track %>
          <%= link_to track_path(track), class: 'delete-icon', method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <h5 class="my-tracks__ready mt-5">Trainings others created</h5>
  <div class="row mb-3">
    <% @tracks.where.not(user: current_user).each do |track| %>
      <div class="col-12 col-md-6 col-lg-4 d-flex justify-content-center">
        <div class="track-card mb-3 d-flex flex-column align-items-center">
          <h3 class="link-styling"><%= track.title %></h3>
          <p>Contains <%= track.steps.count %> steps</p>
          <!-- Button for assign training modal -->
          <button class="btn-secondary-outline mt-3" data-toggle="modal" data-target="#assignTrackModal">Assign</button>
          <%= render 'assign_track_modal', track: track %>
        </div>
      </div>
    <% end %>
  </div>
</div>