config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/dashboard/my-tracks' => "dashboard#my_tracks", :as => :user_root
  root to: 'pages#home'
  get '/dashboard/my-tracks', to: 'dashboard#my_tracks'
  get '/dashboard/track-library', to: 'dashboard#track_library'
  get '/dashboard/team', to: 'dashboard#team'
  get '/dashboard/profile', to: 'dashboard#profile'
  get '/dashboard/settings', to: 'dashboard#settings'

  resources :tracks, except: %i[index show] do
    resources :steps, only: %i[create destroy]
    resources :assignments, only: %i[create]
  end

  resources :assignments, only: %i[show destroy] do
    resources :step_scores, only: %i[update]
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user
  has_many :steps, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :assigned_users, through: :assignments, source: :user

  validates :title, presence: true
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[destroy edit update]

  def index
    @tracks = policy_scope(Track)
    @track = Track.new
  end

  def edit
    authorize @track
  end

  def update
    # authorize @track
    # if @track.save
    #   redirect_to track_path(@track)
    # else
    #   render "index"
    # end
  end

  def create
    @track = Track.new(track_params)
    authorize @track
    @tracks = policy_scope(Track)
    @track.user = current_user
    if @track.save
      redirect_to dashboard_track_library_path
    else
      render "dashboard/track_library"
    end
  end

  def destroy
    authorize @track
    @track.destroy
    redirect_to dashboard_track_library_path
  end

  private

  def set_track
    @track = Track.find(params[:id])
  end

  def track_params
    params.require(:track).permit(:title, :is_global)
  end
end

app/views/tracks/edit.html.erb
<div class="container d-flex flex-column align-items-center"> 
  <h2><%= @track.title %></h2>
  <h3>Your steps</h3>
  <% @track.steps.each do |step| %>
    <div class="card step-card my-3">
      <div class="card-body d-flex justify-content-between align-items-center">
        <!-- <p><%= step.content_type %></p> -->
        <% if step.media.attached? %>
          <%= media_link step %>
        <% else %>
          <p>No file</p>
        <% end %>
        <p><strong><%= step.title %></strong></p>
        <%= link_to track_step_path(@track, step), class: "delete-styling", method: :delete, data: {confirm: 'Are you sure?'} do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  <!-- Button for Modal -->
  <a class="btn-dashboard-1 btn-add-step" data-toggle="modal" data-target="#exampleModal">
    <i class="fas fa-plus"></i>
  </a>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <strong class="modal-title" id="exampleModalLabel">Add a step to the training</strong>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= simple_form_for [@track, Step.new] do |f| %>
        <%= f.input :title, input_html: { maxlength: '30' } %>
        <%= f.input :content_type, collection: ['PDF', 'Image', 'Video'], selected: 'PDF' %>
        <%= f.input :media, as: :file %>
        <%= f.button :submit, 'Add', class: 'btn-secondary' %>
      <% end %>
      </div>
    </div>
  </div>
</div>