config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/dashboard/my-tracks' => "dashboard#my_tracks", :as => :user_root
  root to: 'pages#home'
  get '/dashboard/my-tracks', to: 'dashboard#my_tracks'
  get '/dashboard/track-library', to: 'dashboard#track_library'
  get '/dashboard/team', to: 'dashboard#team'
  get '/dashboard/profile', to: 'dashboard#profile'
  get '/dashboard/settings', to: 'dashboard#settings'

  resources :tracks, except: %i[index show] do
    resources :steps, only: %i[create destroy]
    resources :assignments, only: %i[create]
  end

  resources :assignments, only: %i[show destroy] do
    resources :step_scores, only: %i[update]
  end
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :track
  has_many :step_scores, dependent: :destroy

  def completed?
    num_of_steps == num_of_steps_completed
  end

  def num_of_steps
    step_scores.count
  end

  def num_of_steps_completed
    step_scores.reject { |step_score| step_score.completed_at.nil? }.count
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[show destroy]

  def show
  end

  def create
    authorize @assignment = Assignment.new
    @assignment.user = User.find(assignment_params[:user_id])
    @assignment.track = Track.find(params[:track_id])
    @assignment.track.steps.each do |step|
      StepScore.create(assignment: @assignment, step: step)
    end
    if @assignment.save
      redirect_to dashboard_track_library_path
    else
      render "/dashboard/track-library"
    end
  end

  def destroy
    @assignment.destroy
    redirect_to dashboard_settings_path
  end

  private

  def set_assignment
    @assignment = Assignment.find(params[:id])
    authorize @assignment
  end

  def assignment_params
    params.require(:assignment).permit(:user_id)
  end
end

app/views/assignments/show.html.erb
<div class="container mt-3">
  <h2 class="text-center"><%= @assignment.track.title %></h2>
  <div class="assignment-container d-flex">
    <div class="assignment-chart">
      <p class="assignment-chart__well-done <%= assignment_completed?(@assignment) ? "" : "hidden"%>">Well done!</p>
      <div class="chart-wrapper">
        <canvas id="myChart" data-score=<%= assignment_score(@assignment) %>></canvas>
      </div>
      <p><%= assignment_score(@assignment) %>% completed</p>
    </div>

    <div class="assignment-steps">
      <% @assignment.step_scores.order(created_at: :asc).each_with_index do |step_score, index| %>
        <div class="assignment-step">
          <div class="assignment-step__score">
            <i class="far fa-<%= step_score.completed_at.nil? ? "" : "dot-" %>circle"></i>
            <% unless index == (@assignment.step_scores.length - 1) || step_score.completed_at.nil? %>
              <div class="assignment-step__score__link"></div>
            <% end %>
          </div>
          <div class="assignment-step__content">
            <h3><%= step_score.step.title %></h3>
            <%= media_icon step_score.step %>
            <div class="assignment-step__content__buttons">
              <% if step_score.step.media.attached? %>
                <%= media_link_content step_score.step %>
              <% end %>
              <%= link_to assignment_step_score_path(@assignment, step_score), class: "btn-mark-as ml-2", method: :patch, remote: true do %>
                <%= step_score.completed_at.nil? ? "Mark as done" : "Mark as undone" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>