config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/dashboard/my-tracks' => "dashboard#my_tracks", :as => :user_root
  root to: 'pages#home'
  get '/dashboard/my-tracks', to: 'dashboard#my_tracks'
  get '/dashboard/track-library', to: 'dashboard#track_library'
  get '/dashboard/team', to: 'dashboard#team'
  get '/dashboard/profile', to: 'dashboard#profile'
  get '/dashboard/settings', to: 'dashboard#settings'

  resources :tracks, except: %i[index show] do
    resources :steps, only: %i[create destroy]
    resources :assignments, only: %i[create]
  end

  resources :assignments, only: %i[show destroy] do
    resources :step_scores, only: %i[update]
  end
end

app/views/shared/_back_btn.html.erb
<% unless back_button_path(params).nil? %>
  <%= link_to back_button_path(params), class: 'btn-dashboard-1 btn-back' do %>
    <i class="fas fa-long-arrow-alt-left"></i>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__social-links">
    <span>Follow us</span>
    <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-fw fa-github"></i></a>
    <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
    <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
  </div>
  <div class="footer__copyrights">
    <p>
      This website was coded with lots of <i class="fas fa-coffee"></i> and
      <i class="fas fa-heart"></i> at Nubi © 2021.
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon <%= is_home ? "navbar-home" : '' %>">
  <div class="navbar-brand">
  <%= link_to root_path do %>
    <%= image_tag "logo.png" %>
  <% end %>
  </div>

  <span class="navbar-text ml-5"><%= tab %></span>
  <div id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if is_home %>
          <li class="nav-item">
          <%= link_to "Dashboard", dashboard_path, class: "nav-link nav-btn-dashboard" %>
          </li>
        <% else %>
          <li class="nav-item">
          <span class="nav-link nav-link__username"><%= "#{current_user.first_name} #{current_user.last_name}" %></span>
          </li>
          <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <i class="fas fa-power-off"></i>
          <% end %>
          </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link login" do %>
            <i class="fas fa-sign-in-alt"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<ul class="nav nav-tabs">
  <div class="nav-items-top">
    <li class="nav-item">
      <%= link_to dashboard_my_tracks_path, class: "nav-link #{tab == 'my-tracks' ? 'active' : ''}" do %>
        <i class="fas fa-poll"></i>
      <% end %>
      <div class="nav-label">My Training</div>
    </li>
    <% if current_user.is_manager? %>
    <li class="nav-item">
      <%= link_to dashboard_track_library_path, class: "nav-link #{tab == 'track-library' ? 'active' : ''}" do %>
        <i class="fab fa-hive"></i>
      <% end %>
      <div class="nav-label">Training Library</div>
    </li>
    <% end %>
    <li class="nav-item">
      <%= link_to dashboard_team_path, class: "nav-link #{tab == 'team' ? 'active' : ''}" do %>
        <i class="fas fa-users"></i>
      <% end %>
      <div class="nav-label">Team</div>
    </li>
    <li class="nav-item">
      <%= link_to dashboard_profile_path, class: "nav-link #{tab == 'profile' ? 'active' : ''}" do %>
        <i class="fas fa-user-alt"></i>
      <% end %>
      <div class="nav-label">Profile</div>
    </li>
  </div>
  <div class="nav-items-bottom">
    <li class="nav-item">
      <%= link_to dashboard_settings_path, class: "nav-link #{tab == 'settings' ? 'active' : ''}" do %>
        <i class="fas fa-cog"></i>
      <% end %>
      <div class="nav-label">Settings</div>
    </li>
  </div>
</ul>